config/routes.rb
Rails.application.routes.draw do
  # get 'stpre/index'
  root 'stpre#index', as: 'stpre_index'

  resources :keduas
  resources :products
  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kedua.rb
class Kedua < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
	# test comen
	# coba lagi
	# ada lagi
	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_then_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(png|jpg|gif)\Z}i,
		message: 'must be a URL for GIF, JPG or PNG image . '
	}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/keduas_controller.rb
class KeduasController < ApplicationController
  before_action :set_kedua, only: [:show, :edit, :update, :destroy]

  # GET /keduas
  # GET /keduas.json
  def index
    @keduas = Kedua.all
  end

  # GET /keduas/1
  # GET /keduas/1.json
  def show
  end

  # GET /keduas/new
  def new
    @kedua = Kedua.new
  end

  # GET /keduas/1/edit
  def edit
  end

  # POST /keduas
  # POST /keduas.json
  def create
    @kedua = Kedua.new(kedua_params)

    respond_to do |format|
      if @kedua.save
        format.html { redirect_to @kedua, notice: 'Kedua was successfully created.' }
        format.json { render :show, status: :created, location: @kedua }
      else
        format.html { render :new }
        format.json { render json: @kedua.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keduas/1
  # PATCH/PUT /keduas/1.json
  def update
    respond_to do |format|
      if @kedua.update(kedua_params)
        format.html { redirect_to @kedua, notice: 'Kedua was successfully updated.' }
        format.json { render :show, status: :ok, location: @kedua }
      else
        format.html { render :edit }
        format.json { render json: @kedua.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keduas/1
  # DELETE /keduas/1.json
  def destroy
    @kedua.destroy
    respond_to do |format|
      format.html { redirect_to keduas_url, notice: 'Kedua was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kedua
      @kedua = Kedua.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kedua_params
      params.require(:kedua).permit(:nama, :alamat, :no_hp)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
# ddddddddd
# lagilagi
# asdjkfhkajsd
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
  def masuk
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

app/controllers/stpre_controller.rb
class StpreController < ApplicationController
  def index
  	@products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keduas_helper.rb
module KeduasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/stpre_helper.rb
module StpreHelper
end

app/views/keduas/_form.html.erb
<%= form_with(model: kedua, local: true) do |form| %>
  <% if kedua.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kedua.errors.count, "error") %> prohibited this kedua from being saved:</h2>

      <ul>
      <% kedua.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama %>
    <%= form.text_field :nama, id: :kedua_nama %>
  </div>

  <div class="field">
    <%= form.label :alamat %>
    <%= form.text_area :alamat, id: :kedua_alamat %>
  </div>

  <div class="field">
    <%= form.label :no_hp %>
    <%= form.number_field :no_hp, id: :kedua_no_hp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/keduas/edit.html.erb
<h1>Editing Kedua</h1>

<%= render 'form', kedua: @kedua %>

<%= link_to 'Show', @kedua %> |
<%= link_to 'Back', keduas_path %>

app/views/keduas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Keduas</h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Alamat</th>
      <th>No hp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keduas.each do |kedua| %>
      <tr>
        <td><%= kedua.nama %></td>
        <td><%= kedua.alamat %></td>
        <td><%= kedua.no_hp %></td>
        <td><%= link_to 'Show', kedua %></td>
        <td><%= link_to 'Edit', edit_kedua_path(kedua) %></td>
        <td><%= link_to 'Destroy', kedua, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kedua', new_kedua_path %>

app/views/keduas/new.html.erb
<h1>New Kedua</h1>

<%= render 'form', kedua: @kedua %>

<%= link_to 'Back', keduas_path %>

app/views/keduas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @kedua.nama %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @kedua.alamat %>
</p>

<p>
  <strong>No hp:</strong>
  <%= @kedua.no_hp %>
</p>

<%= link_to 'Edit', edit_kedua_path(@kedua) %> |
<%= link_to 'Back', keduas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragrog Books Online Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
  <div id="banner">
  <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
  <span class="title"><%= @page_title %></span>
  </div>
  <div id="columns">
	  <div id="side">
	  	<ul>
	  		<li><a href="http://www....">Home</a></li>
	  		<li><a href="http://www....">Question</a></li>
	  		<li><a href="http://www....">News</a></li>
	  		<li><a href="http://www....">Contact</a></li>
	  	</ul>
	  </div>
	  <div id="main">
	  	<%= yield %>
	  </div>
  </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td>
      <%= image_tag(product.image_url, class: 'list_image') %>
    </td>
    <td class="list_description">
      <dl>
        <dt><%= product.title %></dt>
        <dt><%= truncate(strip_tags(product.description), length: 80) %></dt>
      </dl>
    </td>
    <td class="list_action">
      <%= link_to 'Show', product %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
    <% end %>
</table>

<br>

<%= link_to 'Buat Product baru', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
Its now <%= Time.now %>
<%= ar = [1,2,7,8,5,6].sort %>
<%= ar.each {|line| line} %>
say <a href="/say/hello"> helo </a>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>this is a @time</p>

say <a href="/say/goodbye"> bye </a>
time to say 
<%= link_to "Goodbye", say_goodbye_path %>!

app/views/stpre/index.html.erb
<p id="notice"><%= notice %></p>
<h1> Your Pragmatic Catalog </h1>

<% @products.each do |product| %>
<div class="entry">
	<%= image_tag(product.image_url) %>
	<h3> <%= product.title %> </h3>
	<p><span class="krp"><%= sanitize(product.description) %></span>></p>
	<div class="price_line">
		<span class="price"><%= number_to_currency(product.price) %></span>
	</div>
</div>
<% end %>